name: This is the First Github Actions Script. 

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs: 
  demo:
    runs-on: ubuntu-latest
    steps: 
      - name: This will execute the Script
        run: echo "Welcome to the Github Actions!!!!!"
        
      - name: Show current working directory
        run: pwd

      - name: List the directory
        run: ls -l

      - name: Create a sample file
        run: echo "Hello Gihtub Actions" > sample.txt 

      - name: Display the file content 
        run: cat sample.txt
