name: This is the First Github Actions Script. 

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs: 
  demo:
    runs-on: ubuntu-latest
    steps: 
      - name: This will execute the Script
        run: echo "Welcome to the Github Actions!!!!!"
        
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: List the repository file 
        run: ls -la
