name: Context Demo

on:
  push:
  
jobs: 
  job-01: 
    runs-on: ubuntu-latest
    steps:
      - name: Repo Information
        run: echo "${{github.repository}}
      - name: Branch Information 
        run: echo "${{github.ref}}"
      - name: OS 
        run: echo "${{runner.os}}"
